version: '3.5'

services:
  elasticsearch:
    build: .
    image: es
    container_name: es
    hostname: es
#    tty: true
    ports:
      - "9200:9200"
    networks:
      - esnet
  web_app:
    build: ./Flask
    image: app
    container_name: app
    hostname: app
    tty: true
    ports:
      - "5000:5000"
    networks:
      - esnet
networks:
  esnet:
