version: '3.5'

services:
  elasticsearch:
    build: ./Elastic
    image: es
    container_name: es
    hostname: es
#    tty: true
    ports:
      - "9200:9200"
    networks:
      - esnet
  web_app:
    build: ./Flask
    image: flask_es
    container_name: flask_es
    hostname: flask_es
    tty: true
    ports:
      - "5000:5000"
    networks:
      - esnet
networks:
  esnet:
